# Generated by Django 4.0.4 on 2022-04-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_txt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_clas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clas_txt', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle_brand')),
                ('car_clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klasa', to='app.vehicle_generation')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle_generation')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle_brand',
            name='cars_in_clas',
            field=models.ManyToManyField(through='app.Vehicle_clas', to='app.vehicle_generation'),
        ),
    ]
