# Generated by Django 4.0.4 on 2022-04-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_brand',
            name='cars_in_clas',
            field=models.ManyToManyField(through='app.Vehicle_segment', to='app.vehicle_generation'),
        ),
        migrations.DeleteModel(
            name='Vehicle_clas',
        ),
        migrations.AddField(
            model_name='vehicle_segment',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle_brand'),
        ),
        migrations.AddField(
            model_name='vehicle_segment',
            name='car_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klasa', to='app.vehicle_generation'),
        ),
        migrations.AddField(
            model_name='vehicle_segment',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle_generation'),
        ),
    ]
