# Generated by Django 4.0.4 on 2022-04-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_vehicle_segment_alter_vehicle_brand_cars_in_clas_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle_generation',
            old_name='generation_txt',
            new_name='generation_name',
        ),
    ]
