# Generated by Django 4.0.4 on 2022-04-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_generation_txt_vehicle_generation_generation_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand')),
                ('car_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.segment')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle_segment',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='vehicle_segment',
            name='car_segment',
        ),
        migrations.RemoveField(
            model_name='vehicle_segment',
            name='generation',
        ),
        migrations.RenameModel(
            old_name='Vehicle_generation',
            new_name='Generation',
        ),
        migrations.DeleteModel(
            name='Vehicle_brand',
        ),
        migrations.DeleteModel(
            name='Vehicle_segment',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.generation'),
        ),
        migrations.AddField(
            model_name='brand',
            name='cars_in_clas',
            field=models.ManyToManyField(through='app.Vehicle', to='app.generation'),
        ),
    ]
