# Generated by Django 4.0.4 on 2022-04-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_segment_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='car_segment',
            new_name='model',
        ),
    ]
